package com.oracle.hr.model.uiview.common;

import java.util.List;

import oracle.jbo.Key;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 17 11:40:22 EET 2019
// ---------------------------------------------------------------------
public interface AttachmentsVO extends ViewObject {

    void deleteAttachments(List<Key> attKey);
}

