package com.oracle.hr.model.module.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 13 13:38:36 EET 2019
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    void setFileData(String name, String path, String contTyp);

    void deleteSelectedRows(List selectedRowIndexes);
}

