package com.oracle.hr.model.uiview;

import com.oracle.hr.model.uiview.common.AttachmentsVO;

import java.util.List;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 17 11:37:52 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AttachmentsVOImpl extends ViewObjectImpl implements AttachmentsVO {
    /**
     * This is the default constructor (do not remove).
     */
    public AttachmentsVOImpl() {
    }
    
    public void deleteAttachments(List<Key> attKey){
        if(attKey !=null){
            for(Key k:attKey){
                Row[] row = this.findByKey(k, 1);
                if(row !=null && row.length==1){
                    AttachmentsVORowImpl r = (AttachmentsVORowImpl)row[0];
                    r.remove();
                }
            }
        }
    }
    
}

