package com.oracle.hr.model.module;

import com.oracle.hr.model.module.common.AppModuleAM;


import com.oracle.hr.model.uiview.AttachmentsVOImpl;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 13 13:32:47 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl implements AppModuleAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for Attachments1.
     * @return Attachments1
     */
    public AttachmentsVOImpl getAttachments1() {
        return (AttachmentsVOImpl) findViewObject("Attachments1");
    }

    /**
     * Container's getter for Category1.
     * @return Category1
     */
    public ViewObjectImpl getCategory1() {
        return (ViewObjectImpl) findViewObject("Category1");
    }

    /**
     * Container's getter for Employees1.
     * @return Employees1
     */
    public ViewObjectImpl getEmployees1() {
        return (ViewObjectImpl) findViewObject("Employees1");
    }

    /**
     * Container's getter for Messages1.
     * @return Messages1
     */
    public ViewObjectImpl getMessages1() {
        return (ViewObjectImpl) findViewObject("Messages1");
    }

    /**
     * Container's getter for Tender1.
     * @return Tender1
     */
    public ViewObjectImpl getTender1() {
        return (ViewObjectImpl) findViewObject("Tender1");
    }

    /**
     * Container's getter for Attachments2.
     * @return Attachments2
     */
    public AttachmentsVOImpl getAttachments2() {
        return (AttachmentsVOImpl) findViewObject("Attachments2");
    }

    /**
     * Container's getter for Employees2.
     * @return Employees2
     */
    public ViewObjectImpl getEmployees2() {
        return (ViewObjectImpl) findViewObject("Employees2");
    }

    /**
     * Container's getter for Tenders1.
     * @return Tenders1
     */
    public ViewObjectImpl getTenders1() {
        return (ViewObjectImpl) findViewObject("Tenders1");
    }

    /**
     * Container's getter for AttachmentFkVL1.
     * @return AttachmentFkVL1
     */
    public ViewLinkImpl getAttachmentFkVL1() {
        return (ViewLinkImpl) findViewLink("AttachmentFkVL1");
    }
    
    public void setFileData(String name, String path,String contTyp)
           {
           ViewObject fileVo = this.getAttachments2(); 
           Row newRow = fileVo.createRow();
           newRow.setAttribute("Title", name);
           newRow.setAttribute("Type", contTyp);
           newRow.setAttribute("Description", path);
           fileVo.insertRow(newRow);
           this.getDBTransaction().commit();
           fileVo.executeQuery();
           }  
    
    public void deleteSelectedRows(List selectedRowIndexes) {
    
        ViewObjectImpl vo = this.getAttachments2();
        for (int i =0; i < selectedRowIndexes.size(); i++){
            int selectedRowIndex =(Integer) selectedRowIndexes.get(i);
            vo.setCurrentRowAtRangeIndex(selectedRowIndex);
            vo.removeCurrentRow();
        }
        this.getTransaction().commit();
    }
    
}

